apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.headless.service.name" . }}
  labels:
{{ include "kafka.labels" . | indent 4 }}
spec:
  clusterIP: {{ .Values.clusterIp }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
{{ include "kafka.selector" . | indent 4 }}
