apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.service.name" . }}
  labels:
{{ include "kafka.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: kafka-client
  selector:
{{ include "kafka.selector" . | indent 4 }}
