apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr.service.name" . }}
  labels:
{{ include "solr.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.servicePort }}
      name: {{ .Values.service.name }}
  selector:
{{ toYaml .Values.selector | indent 4}}
