---
#  headless  service  for  monogo  statefulset
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
{{ include "mongo.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  clusterIP: None
  selector:
{{ include "mongo.selector" . | indent 6 }}
