# Environment variables for scrapy
env:
  kafka_host: 'kafka-svc'
  bulk_enable: 'yes'
  files_store: "/app/nhs_test_files"

# scrapy image repo public pajmd or private pjmd-ubuntu.cm
image:
  repo: "somerepo"
  tag: v0.0.6
  name: "scrapy-nhs"

command: "/app/docker_send_test_files.sh"